synchronize_notes_from_other_service:
  cron: "* * * * *"
  class: ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
  queue: high
  description: "This job queues synchronization of notes service"
  args:
    job_class: Cron::ExternalNotes::SynchronizerJob
    queue_name: default
    arguments: [ ]
