version: "3"

services:

  web: &web
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    entrypoint: /docker/entrypoints/web-entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./notes:/usr/src/app
    env_file:
      - docker/.env/development/web
      - docker/.env/development/db
      - docker/.env/test/db
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379

  db:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.db
    restart: always
    ports:
      - "3306:3306"
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/entrypoints/docker-entrypoint-initdb.d/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    env_file:
      - docker/.env/development/db
      - docker/.env/test/db

  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db
      - ./docker/entrypoints/docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    env_file:
      - docker/.env/development/mongodb

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  worker:
    <<: *web
    entrypoint: /docker/entrypoints/worker-entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379

  scheduler:
    <<: *web
    entrypoint: /docker/entrypoints/worker-scheduler-entrypoint.sh
    depends_on:
      - db
      - redis
      - worker
    ports: [ ]
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379

  externalnotes:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.externalnotes
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    entrypoint: /docker/entrypoints/externalnotes-entrypoint.sh
    ports:
      - "4567:4567"
    volumes:
      - ./externalnotes:/usr/src/app

volumes:
  db-data:
  mongo-db-data:
