version: "3"

services:

  web:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    entrypoint: ./docker/entrypoints/web-entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - docker/.env/development/web
      - docker/.env/development/db
      - docker/.env/development/redis
      - docker/.env/test/db
    environment:
      RAILS_ENV: development

  db:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.db
    restart: always
    ports:
      - "3306:3306"
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/entrypoints/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - docker/.env/development/db
      - docker/.env/test/db


  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    entrypoint: ./docker/entrypoints/worker-entrypoint.sh
    depends_on:
      - web
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - docker/.env/development/web
      - docker/.env/development/db
      - docker/.env/development/redis
      - docker/.env/test/db
    environment:
      RAILS_ENV: development

volumes:
  db-data:
