version: "3"

services:

  web: &web
    build:
      context: .
      dockerfile: docker/dockerfiles/web.dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    entrypoint: /docker/entrypoints/web-entrypoint.sh
    depends_on:
      - db
      - mongodb
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./notes:/usr/src/app
      - web_gem_cache:/usr/local/bundle/gems
    env_file:
      - docker/.env/development/web
      - docker/.env/development/db
      - docker/.env/development/mongodb
      - docker/.env/development/redis

  db:
    build:
      context: .
      dockerfile: docker/dockerfiles/db.dockerfile
    restart: always
    ports:
      - "3306:3306"
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/entrypoints/docker-entrypoint-initdb.d/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    env_file:
      - docker/.env/development/db

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db
      - ./docker/entrypoints/docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    env_file:
      - docker/.env/development/mongodb

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  worker:
    <<: *web
    entrypoint: /docker/entrypoints/worker-entrypoint.sh
    depends_on:
      - web
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./notes:/usr/src/app
      - web_gem_cache:/usr/local/bundle/gems

  scheduler:
    <<: *web
    entrypoint: /docker/entrypoints/worker-scheduler-entrypoint.sh
    depends_on:
      - web
      - redis
      - worker
    ports: [ ]
    volumes:
      - ./notes:/usr/src/app
      - web_gem_cache:/usr/local/bundle/gems

  externalnotes:
    build:
      context: .
      dockerfile: docker/dockerfiles/externalnotes.dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    entrypoint: /docker/entrypoints/externalnotes-entrypoint.sh
    ports:
      - "4567:4567"
    volumes:
      - ./externalnotes:/usr/src/app
      - externalnotes_gem_cache:/usr/local/bundle/gems

  notesconsumer:
    build:
      context: .
      dockerfile: docker/dockerfiles/notesconsumer.dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    tty: true
    stdin_open: true
    volumes:
      - ./notesconsumer:/usr/src/app
      - /usr/src/app/node_modules

  mongodb-ui:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    env_file:
      - docker/.env/development/mongodb

volumes:
  db-data:
  mongo-db-data:
  web_gem_cache:
  externalnotes_gem_cache:
