name: "notes"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  test:
    defaults:
      run:
        working-directory: notes
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: notes_test
          MYSQL_USER: notes_test_user
          MYSQL_PASSWORD: notes_test_password
        ports:
          - "3306:3306"
    env:
      RAILS_ENV: test
      MYSQL_DATABASE: notes_test
      MYSQL_USER: notes_test_user
      MYSQL_PASSWORD: notes_test_password
      DATABASE_HOST: 127.0.0.1
    steps:
      - uses: actions/checkout@v2
      - name: Echo ci environment variable
        run: echo $CI
      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: default
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Setup database
        run: bundle exec rails db:create
      - name: Run tests
        run: bundle exec rspec spec
