name: "notes"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  test:
    defaults:
      run:
        working-directory: notes
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: test_database
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: database_user
          MYSQL_PASSWORD:
        ports:
          - "3306:3306"
    env:
      RAILS_ENV: test
      DATABASE_PORT: 3306
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: default
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Setup database
        run: bundle exec rails db:create
      - name: Run tests
        run: bundle exec rspec spec
