name: "notes"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  test:
    defaults:
      run:
        working-directory: notes
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_database
        ports:
          - "3306:3306"
    env:
      RAILS_ENV: test
      MYSQL_TEST_DATABASE: test_database
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_TEST_USER: root
      MYSQL_TEST_PASSWORD:
      DATABASE_HOST: 127.0.0.1
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: default
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Setup database
        run: RAILS_ENV=test bundle exec rails db:create --trace
      - name: Run tests
        run: RAILS_ENV=test bundle exec rspec spec
